plugins:
  discourse_apim_azure_service_name:
    type: string
    default: ""
  discourse_apim_azure_subscription_id:
    type: string
    default: ""
  discourse_apim_azure_resource_group_name:
    type: string
    default: ""
  discourse_apim_azure_management_key:
    type: string
    default: ""
    secret: true
  discourse_apim_reporting_enabled:
    type: boolean
    default: false
  discourse_apim_azure_additional_reporting_service_name:
    type: string
    default: ""
  discourse_apim_azure_additional_reporting_management_key:
    type: string
    default: ""
    secret: true